// seed-labs.js
// Popula content/labs/items com laboratórios que incluem uma sequência de comandos
// e a saída simulada de cada um — alimenta o simulador de CLI (cli-simulator.js).
// Mesmo padrão de seed das outras coleções: só grava uma vez.

import { doc, getDoc, setDoc, writeBatch, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";
import { db } from "./firebase-config.js";

const labsExemplo = [
  {
    id: "lab-2.1-vlan",
    topicId: "m08-01",
    titulo: "Configuração básica de VLANs e Trunk 802.1Q",
    ferramenta: "EVE-NG",
    dispositivo: "Switch",
    promptInicial: "Switch>",
    topologiaDescricao: "2 switches (SW1, SW2) conectados por trunk, cada um com 2 hosts em VLANs diferentes (10 e 20).",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Switch#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Switch(config)#" },
      { instrucao: "Crie a VLAN 10.", cmd: "vlan 10", saida: "", promptDepois: "Switch(config-vlan)#" },
      { instrucao: "Dê um nome à VLAN 10.", cmd: "name VENDAS", saida: "", promptDepois: "Switch(config-vlan)#" },
      { instrucao: "Volte pro modo de configuração global.", cmd: "exit", saida: "", promptDepois: "Switch(config)#" },
      { instrucao: "Entre na interface fa0/24 (porta do trunk).", cmd: "interface fa0/24", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Coloque a porta em modo trunk.", cmd: "switchport mode trunk", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Permita as VLANs 10 e 20 nesse trunk.", cmd: "switchport trunk allowed vlan 10,20", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Switch#" },
      { instrucao: "Confirme as VLANs criadas.", cmd: "show vlan brief", saida: "VLAN Name                             Status    Ports\n---- -------------------------------- --------- -------\n1    default                          active    Fa0/1, Fa0/2\n10   VENDAS                           active\n20   TI                               active", promptDepois: "Switch#" },
    ],
    errosComuns: [
      "Esquecer de permitir a VLAN no trunk (`switchport trunk allowed vlan`) — tráfego não passa.",
      "Deixar a porta como `dynamic auto` dos dois lados — trunk não negocia.",
      "Nativa VLAN diferente nas duas pontas do trunk — gera warning de mismatch.",
    ],
  },
  {
    id: "lab-3.3-ospf",
    topicId: "m22-01",
    titulo: "OSPFv2 de área única entre 3 roteadores",
    ferramenta: "PNETLab",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "R1 — R2 — R3 em topologia linear, todos na área 0.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Habilite o OSPF processo 1.", cmd: "router ospf 1", saida: "", promptDepois: "Router(config-router)#" },
      { instrucao: "Defina o router-id manualmente.", cmd: "router-id 1.1.1.1", saida: "", promptDepois: "Router(config-router)#" },
      { instrucao: "Anuncie a rede na área 0.", cmd: "network 10.0.0.0 0.0.0.3 area 0", saida: "", promptDepois: "Router(config-router)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Verifique os vizinhos OSPF formados.", cmd: "show ip ospf neighbor", saida: "Neighbor ID     Pri   State           Dead Time   Address         Interface\n2.2.2.2           1   FULL/BDR        00:00:38    10.0.0.2        GigabitEthernet0/0", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Wildcard mask errada na rede anunciada (inverter máscara com wildcard).",
      "Roteadores em áreas diferentes sem querer — vizinhança nunca forma.",
      "Interface passiva mal configurada, impedindo formação de vizinhança onde não devia.",
    ],
  },
  {
    id: "lab-4.1-nat",
    topicId: "m43-03",
    titulo: "NAT dinâmico com PAT (sobrecarga)",
    ferramenta: "EVE-NG",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "R1 com interface interna (LAN) e externa (simulando internet), 2 hosts na LAN.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Entre na interface interna (LAN).", cmd: "interface g0/0", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Marque essa interface como NAT inside.", cmd: "ip nat inside", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Volte e entre na interface externa.", cmd: "interface g0/1", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Marque essa interface como NAT outside.", cmd: "ip nat outside", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Saia pro modo global.", cmd: "exit", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Crie uma ACL definindo a rede interna a traduzir.", cmd: "access-list 1 permit 192.168.1.0 0.0.0.255", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Configure o NAT com sobrecarga (PAT).", cmd: "ip nat inside source list 1 interface g0/1 overload", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Verifique as traduções ativas.", cmd: "show ip nat translations", saida: "Pro Inside global      Inside local       Outside local      Outside global\ntcp 203.0.113.1:1024   192.168.1.10:1024  8.8.8.8:80         8.8.8.8:80", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Esquecer de marcar uma das interfaces como inside/outside — NAT não traduz nada.",
      "ACL mal escrita cobrindo a rede errada.",
      "Esquecer `overload` — permite só 1 tradução simultânea em vez de várias com portas diferentes.",
    ],
  },
  {
    id: "lab-5.4-acl",
    topicId: "m36-02",
    titulo: "ACL estendida bloqueando tráfego específico",
    ferramenta: "PNETLab",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "R1 entre duas redes, bloqueando acesso HTTP de uma sub-rede específica ao servidor.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Bloqueie tráfego HTTP dessa sub-rede ao servidor.", cmd: "access-list 101 deny tcp 192.168.10.0 0.0.0.255 host 192.168.20.100 eq 80", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Permita todo o resto do tráfego.", cmd: "access-list 101 permit ip any any", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Entre na interface de entrada do tráfego.", cmd: "interface g0/0", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Aplique a ACL na direção de entrada.", cmd: "ip access-group 101 in", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Verifique os contadores da ACL.", cmd: "show access-lists 101", saida: "Extended IP access list 101\n    10 deny tcp 192.168.10.0 0.0.0.255 host 192.168.20.100 eq www (3 matches)\n    20 permit ip any any (128 matches)", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Aplicar a ACL do lado errado (in vs out).",
      "Esquecer o `permit ip any any` no final — bloqueia tudo sem querer (deny implícito).",
      "Ordem das regras errada — regra mais específica precisa vir antes da mais genérica.",
    ],
  },
  {
    id: "lab-2.4-etherchannel",
    topicId: "m10-03",
    titulo: "EtherChannel com LACP entre dois switches",
    ferramenta: "EVE-NG",
    dispositivo: "Switch",
    promptInicial: "Switch>",
    topologiaDescricao: "SW1 e SW2 conectados por 2 links físicos agrupados em 1 EtherChannel lógico.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Switch#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Switch(config)#" },
      { instrucao: "Selecione as duas interfaces físicas de uma vez.", cmd: "interface range g0/1-2", saida: "", promptDepois: "Switch(config-if-range)#" },
      { instrucao: "Agrupe as interfaces em LACP ativo.", cmd: "channel-group 1 mode active", saida: "Creating a port-channel interface Port-channel 1", promptDepois: "Switch(config-if-range)#" },
      { instrucao: "Saia pro modo global.", cmd: "exit", saida: "", promptDepois: "Switch(config)#" },
      { instrucao: "Entre na interface lógica Port-channel 1.", cmd: "interface port-channel 1", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Configure a Port-channel como trunk.", cmd: "switchport mode trunk", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Switch#" },
      { instrucao: "Verifique se o canal formou corretamente.", cmd: "show etherchannel summary", saida: "Group  Port-channel  Protocol    Ports\n------+-------------+-----------+-----------------------------------------------\n1      Po1(SU)         LACP      Gi0/1(P) Gi0/2(P)", promptDepois: "Switch#" },
    ],
    errosComuns: [
      "Modos LACP incompatíveis entre os switches (active-active ou active-passive funcionam; passive-passive não forma o canal).",
      "Interfaces com configurações diferentes (velocidade, duplex, VLAN) antes de agrupar — o channel não sobe.",
    ],
  },
  {
    id: "lab-45-hsrp",
    topicId: "m45-01",
    titulo: "Redundância de gateway com HSRP",
    ferramenta: "PNETLab",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "R1 e R2 compartilhando um gateway virtual pra mesma LAN, com R1 como ativo.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Entre na interface LAN.", cmd: "interface g0/0", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Configure o grupo HSRP 1 com o IP virtual.", cmd: "standby 1 ip 192.168.1.1", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Defina a prioridade pra esse roteador ser o ativo.", cmd: "standby 1 priority 110", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Habilite preempção (assumir o papel ativo quando disponível de novo).", cmd: "standby 1 preempt", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Verifique o status do HSRP.", cmd: "show standby brief", saida: "Interface   Grp  Pri P State    Active          Standby         Virtual IP\nGi0/0       1    110 P Active   local           192.168.1.2     192.168.1.1", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Esquecer de configurar o mesmo IP virtual e número de grupo nos dois roteadores — eles não formam par.",
      "Não habilitar preempt — o roteador de maior prioridade não retoma o papel ativo depois de voltar de uma falha.",
    ],
  },
  {
    id: "lab-27-ipv6static",
    topicId: "m27-02",
    titulo: "Rota estática IPv6",
    ferramenta: "EVE-NG",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "R1 — R2 com endereçamento IPv6, anunciando uma rota estática pra rede remota.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Habilite o roteamento IPv6 unicast.", cmd: "ipv6 unicast-routing", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Crie a rota estática pra rede remota via o próximo salto.", cmd: "ipv6 route 2001:db8:2::/64 2001:db8:12::2", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Verifique a tabela de rotas IPv6.", cmd: "show ipv6 route static", saida: "S   2001:DB8:2::/64 [1/0]\n     via 2001:DB8:12::2", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Esquecer o `ipv6 unicast-routing` — sem isso o roteador não encaminha pacotes IPv6 entre interfaces.",
      "Confundir o endereço de rede de destino com o do próximo salto na hora de digitar a rota.",
    ],
  },
  {
    id: "lab-33-wlc",
    topicId: "m33-01",
    titulo: "Configuração básica de um WLC",
    ferramenta: "PNETLab",
    dispositivo: "WLC",
    promptInicial: "WLC>",
    topologiaDescricao: "Um WLC gerenciando um AP lightweight, criando uma WLAN pra clientes wireless.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "WLC#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "WLC(config)#" },
      { instrucao: "Crie o perfil de WLAN com nome e SSID.", cmd: "wlan ESTUDANTES 1 ESTUDANTES", saida: "", promptDepois: "WLC(config-wlan)#" },
      { instrucao: "Defina a segurança como WPA2/WPA3.", cmd: "security wpa wpa2 wpa3", saida: "", promptDepois: "WLC(config-wlan)#" },
      { instrucao: "Ative essa WLAN.", cmd: "no shutdown", saida: "", promptDepois: "WLC(config-wlan)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "WLC#" },
      { instrucao: "Verifique as WLANs configuradas.", cmd: "show wlan summary", saida: "WLAN ID  WLAN Profile Name / SSID   Status   Interface\n1        ESTUDANTES / ESTUDANTES    UP       management", promptDepois: "WLC#" },
    ],
    errosComuns: [
      "Esquecer de dar `no shutdown` na WLAN — ela fica criada mas inativa.",
      "Não vincular a WLAN a uma Policy Tag/interface correta — os clientes não recebem IP.",
    ],
  },
  {
    id: "lab-36-aclnomeada",
    topicId: "m36-01",
    titulo: "ACL nomeada estendida com edição de linhas",
    ferramenta: "PNETLab",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "R1 filtrando tráfego HTTP e SSH de uma sub-rede específica, usando ACL nomeada.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Crie a ACL nomeada estendida.", cmd: "ip access-list extended BLOQUEIA_HTTP", saida: "", promptDepois: "Router(config-ext-nacl)#" },
      { instrucao: "Adicione a regra bloqueando HTTP dessa sub-rede.", cmd: "deny tcp 192.168.30.0 0.0.0.255 any eq 80", saida: "", promptDepois: "Router(config-ext-nacl)#" },
      { instrucao: "Permita o restante do tráfego.", cmd: "permit ip any any", saida: "", promptDepois: "Router(config-ext-nacl)#" },
      { instrucao: "Saia e aplique a ACL na interface correta.", cmd: "interface g0/1", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Aplique a ACL nomeada na entrada.", cmd: "ip access-group BLOQUEIA_HTTP in", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Verifique a ACL nomeada.", cmd: "show ip access-lists BLOQUEIA_HTTP", saida: "Extended IP access list BLOQUEIA_HTTP\n    10 deny tcp 192.168.30.0 0.0.0.255 any eq www\n    20 permit ip any any", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Esquecer que ACLs nomeadas usam `ip access-list extended <nome>`, não `access-list <número>`.",
      "Não perceber que a ordem das regras importa — a mais específica deve vir antes da genérica.",
    ],
  },
  {
    id: "lab-06-sshmgmt",
    topicId: "m06-02",
    titulo: "Configuração de acesso remoto seguro (SSH)",
    ferramenta: "EVE-NG",
    dispositivo: "Switch",
    promptInicial: "Switch>",
    topologiaDescricao: "Switch de acesso configurado para permitir gerenciamento remoto só via SSH, com senhas criptografadas.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Switch#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Switch(config)#" },
      { instrucao: "Defina o nome do domínio (necessário pra gerar chaves RSA).", cmd: "ip domain-name estudo.local", saida: "", promptDepois: "Switch(config)#" },
      { instrucao: "Gere o par de chaves RSA.", cmd: "crypto key generate rsa", saida: "The name for the keys will be: Switch.estudo.local\nChoose the size of the key modulus...\n% Generating 1024 bit RSA keys, keys will be non-exportable...[OK]", promptDepois: "Switch(config)#" },
      { instrucao: "Crie um usuário local com senha.", cmd: "username admin secret Cisco123!", saida: "", promptDepois: "Switch(config)#" },
      { instrucao: "Entre nas linhas VTY.", cmd: "line vty 0 15", saida: "", promptDepois: "Switch(config-line)#" },
      { instrucao: "Exija login com usuário local.", cmd: "login local", saida: "", promptDepois: "Switch(config-line)#" },
      { instrucao: "Permita só SSH (não Telnet) nessas linhas.", cmd: "transport input ssh", saida: "", promptDepois: "Switch(config-line)#" },
      { instrucao: "Saia e criptografe as senhas em texto plano.", cmd: "end", saida: "", promptDepois: "Switch#" },
    ],
    errosComuns: [
      "Esquecer o `ip domain-name` antes de gerar as chaves RSA — o comando `crypto key generate rsa` nem aparece disponível sem isso.",
      "Deixar `transport input telnet ssh` em vez de só `ssh` — mantém uma porta insegura aberta.",
    ],
  },

  // ===== LOTE V5 — labs dos temas centrais que ainda faltavam =====
  {
    id: "lab-04-switchinit",
    topicId: "m04-04",
    titulo: "Configuração inicial de um switch (hostname, senhas, SVI de gerência)",
    ferramenta: "EVE-NG",
    dispositivo: "Switch",
    promptInicial: "Switch>",
    topologiaDescricao: "Switch de acesso novo, configuração base antes de colocar em produção.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Switch#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Switch(config)#" },
      { instrucao: "Defina o nome do switch.", cmd: "hostname SW-ACESSO-1", saida: "", promptDepois: "SW-ACESSO-1(config)#" },
      { instrucao: "Configure a senha criptografada do modo privilegiado.", cmd: "enable secret Cisco123!", saida: "", promptDepois: "SW-ACESSO-1(config)#" },
      { instrucao: "Entre na SVI da VLAN 99 (gerência).", cmd: "interface vlan 99", saida: "", promptDepois: "SW-ACESSO-1(config-if)#" },
      { instrucao: "Dê um IP de gerência à SVI.", cmd: "ip address 10.99.0.10 255.255.255.0", saida: "", promptDepois: "SW-ACESSO-1(config-if)#" },
      { instrucao: "Ative a SVI.", cmd: "no shutdown", saida: "", promptDepois: "SW-ACESSO-1(config-if)#" },
      { instrucao: "Volte ao global e defina o gateway padrão.", cmd: "ip default-gateway 10.99.0.1", saida: "", promptDepois: "SW-ACESSO-1(config)#" },
      { instrucao: "Criptografe as senhas em texto plano restantes.", cmd: "service password-encryption", saida: "", promptDepois: "SW-ACESSO-1(config)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "SW-ACESSO-1#" },
      { instrucao: "Salve a configuração.", cmd: "copy running-config startup-config", saida: "Destination filename [startup-config]?\nBuilding configuration...\n[OK]", promptDepois: "SW-ACESSO-1#" },
    ],
    errosComuns: [
      "Configurar IP direto numa porta física do switch L2 — em switch de camada 2 o IP de gerência vai numa SVI.",
      "Esquecer o `no shutdown` na SVI — ela nasce desativada.",
      "Não configurar o `ip default-gateway` — o switch não responde a gerência de outra sub-rede.",
    ],
  },
  {
    id: "lab-17-staticv4",
    topicId: "m17-02",
    titulo: "Rotas estáticas IPv4 e rota padrão",
    ferramenta: "PNETLab",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "R1 (LAN 192.168.1.0/24) — R2 (LAN 192.168.2.0/24), link WAN 10.0.0.0/30. R1 sai pra internet por R2.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Em R1: crie a rota pra LAN remota via o IP do R2.", cmd: "ip route 192.168.2.0 255.255.255.0 10.0.0.2", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Em R1: crie a rota padrão apontando pra R2.", cmd: "ip route 0.0.0.0 0.0.0.0 10.0.0.2", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Confira a tabela de roteamento.", cmd: "show ip route", saida: "Gateway of last resort is 10.0.0.2 to network 0.0.0.0\n\nS*    0.0.0.0/0 [1/0] via 10.0.0.2\n      192.168.2.0/24 [1/0] via 10.0.0.2\nC     192.168.1.0/24 is directly connected, GigabitEthernet0/0", promptDepois: "Router#" },
      { instrucao: "Teste a conectividade fim a fim.", cmd: "ping 192.168.2.1", saida: "!!!!!\nSuccess rate is 100 percent (5/5)", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Configurar a rota só num sentido — sem a rota de volta em R2, o ping sai mas a resposta não volta.",
      "Trocar máscara por wildcard na rota estática (é máscara normal aqui).",
      "Apontar o next-hop pro próprio IP local em vez do IP do vizinho.",
    ],
  },
  {
    id: "lab-18-svi",
    topicId: "m18-02",
    titulo: "Roteamento inter-VLAN com SVI (switch de camada 3)",
    ferramenta: "EVE-NG",
    dispositivo: "Switch",
    promptInicial: "Switch>",
    topologiaDescricao: "Switch L3 com VLAN 10 (dados) e VLAN 20 (voz), roteando entre elas via SVIs.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Switch#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Switch(config)#" },
      { instrucao: "Habilite o roteamento IP no switch.", cmd: "ip routing", saida: "", promptDepois: "Switch(config)#" },
      { instrucao: "Crie a SVI da VLAN 10.", cmd: "interface vlan 10", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Dê o IP de gateway da VLAN 10.", cmd: "ip address 192.168.10.1 255.255.255.0", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Ative a SVI.", cmd: "no shutdown", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Crie a SVI da VLAN 20.", cmd: "interface vlan 20", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Dê o IP de gateway da VLAN 20.", cmd: "ip address 192.168.20.1 255.255.255.0", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Ative a SVI.", cmd: "no shutdown", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Switch#" },
      { instrucao: "Confirme que as SVIs estão up e roteando.", cmd: "show ip route connected", saida: "C    192.168.10.0/24 is directly connected, Vlan10\nC    192.168.20.0/24 is directly connected, Vlan20", promptDepois: "Switch#" },
    ],
    errosComuns: [
      "Esquecer o `ip routing` — as SVIs sobem mas o switch não roteia entre elas.",
      "SVI fica 'down/down' porque nenhuma porta de acesso naquela VLAN está ativa.",
      "Hosts com o gateway apontando pro IP errado (tem que ser o IP da SVI da sua VLAN).",
    ],
  },
  {
    id: "lab-18-routerstick",
    topicId: "m18-01",
    titulo: "Roteamento inter-VLAN com router-on-a-stick",
    ferramenta: "PNETLab",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "R1 ligado a SW1 por um único link trunk; subinterfaces roteiam VLAN 10 e VLAN 20.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Ative a interface física (sem IP).", cmd: "interface g0/0", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Suba a interface física.", cmd: "no shutdown", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Crie a subinterface da VLAN 10.", cmd: "interface g0/0.10", saida: "", promptDepois: "Router(config-subif)#" },
      { instrucao: "Associe a subinterface à VLAN 10 (802.1Q).", cmd: "encapsulation dot1Q 10", saida: "", promptDepois: "Router(config-subif)#" },
      { instrucao: "Dê o IP de gateway da VLAN 10.", cmd: "ip address 192.168.10.1 255.255.255.0", saida: "", promptDepois: "Router(config-subif)#" },
      { instrucao: "Crie a subinterface da VLAN 20.", cmd: "interface g0/0.20", saida: "", promptDepois: "Router(config-subif)#" },
      { instrucao: "Associe à VLAN 20.", cmd: "encapsulation dot1Q 20", saida: "", promptDepois: "Router(config-subif)#" },
      { instrucao: "Dê o IP de gateway da VLAN 20.", cmd: "ip address 192.168.20.1 255.255.255.0", saida: "", promptDepois: "Router(config-subif)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Verifique as subinterfaces.", cmd: "show ip interface brief", saida: "Interface              IP-Address      OK? Method Status   Protocol\nGigabitEthernet0/0     unassigned      YES unset  up       up\nGigabitEthernet0/0.10  192.168.10.1    YES manual up       up\nGigabitEthernet0/0.20  192.168.20.1    YES manual up       up", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Esquecer `no shutdown` na interface física — todas as subinterfaces ficam down.",
      "Número de VLAN no `encapsulation dot1Q` diferente do configurado no switch.",
      "Porta do switch ligada ao roteador não configurada como trunk.",
    ],
  },
  {
    id: "lab-19-dhcp",
    topicId: "m19-01",
    titulo: "Servidor DHCP no IOS com exclusão de endereços e relay",
    ferramenta: "EVE-NG",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "R1 é servidor DHCP pra LAN 192.168.10.0/24; hosts de outra sub-rede alcançam via ip helper-address.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Exclua o range reservado pra gateways/servidores.", cmd: "ip dhcp excluded-address 192.168.10.1 192.168.10.10", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Crie o pool DHCP.", cmd: "ip dhcp pool LAN10", saida: "", promptDepois: "Router(dhcp-config)#" },
      { instrucao: "Defina a rede distribuída.", cmd: "network 192.168.10.0 255.255.255.0", saida: "", promptDepois: "Router(dhcp-config)#" },
      { instrucao: "Defina o gateway padrão entregue aos clientes.", cmd: "default-router 192.168.10.1", saida: "", promptDepois: "Router(dhcp-config)#" },
      { instrucao: "Defina o servidor DNS entregue aos clientes.", cmd: "dns-server 8.8.8.8", saida: "", promptDepois: "Router(dhcp-config)#" },
      { instrucao: "Volte ao global e configure o relay numa interface de outra LAN.", cmd: "interface g0/2", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Aponte os broadcasts DHCP dessa LAN pro servidor.", cmd: "ip helper-address 192.168.10.1", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Confira as concessões (leases) ativas.", cmd: "show ip dhcp binding", saida: "IP address        Client-ID/Hardware address   Lease expiration        Type\n192.168.10.11     0100.1122.3344.55            Mar 02 2026 10:15 AM     Automatic", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Não excluir o IP do gateway — o servidor pode entregá-lo a um host e gerar conflito.",
      "Máscara errada no `network` do pool.",
      "Esperar que o DHCP atravesse sub-redes sem `ip helper-address` — broadcast não é roteado.",
    ],
  },
  {
    id: "lab-40-portsec",
    topicId: "m40-01",
    titulo: "Port Security com aprendizado sticky e modo de violação",
    ferramenta: "PNETLab",
    dispositivo: "Switch",
    promptInicial: "Switch>",
    topologiaDescricao: "Porta de acesso Fa0/1 liberada pra um único host; qualquer MAC extra dispara violação.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Switch#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Switch(config)#" },
      { instrucao: "Entre na interface de acesso.", cmd: "interface fa0/1", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Force a porta como acesso (port-security exige isso).", cmd: "switchport mode access", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Habilite o Port Security.", cmd: "switchport port-security", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Limite a 1 endereço MAC.", cmd: "switchport port-security maximum 1", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Aprenda o MAC atual de forma sticky.", cmd: "switchport port-security mac-address sticky", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Defina o modo de violação como restrict.", cmd: "switchport port-security violation restrict", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Switch#" },
      { instrucao: "Verifique o estado do Port Security.", cmd: "show port-security interface fa0/1", saida: "Port Security              : Enabled\nPort Status                : Secure-up\nViolation Mode             : Restrict\nMaximum MAC Addresses      : 1\nTotal MAC Addresses        : 1\nSticky MAC Addresses       : 1\nSecurity Violation Count   : 0", promptDepois: "Switch#" },
    ],
    errosComuns: [
      "Deixar a porta em `dynamic auto` — o Port Security não ativa em porta que ainda pode virar trunk.",
      "Confundir os modos: shutdown coloca em err-disabled; restrict/protect só descartam.",
      "Usar sticky e não salvar a config — os MACs aprendidos se perdem no reload.",
    ],
  },
  {
    id: "lab-35-vtyacl",
    topicId: "m35-01",
    titulo: "ACL padrão restringindo o acesso administrativo (VTY)",
    ferramenta: "EVE-NG",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "Só a estação de gerência 10.1.1.10 pode abrir SSH no roteador; o resto é recusado.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Crie a ACL padrão permitindo só o host de gerência.", cmd: "access-list 10 permit host 10.1.1.10", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Entre nas linhas VTY.", cmd: "line vty 0 15", saida: "", promptDepois: "Router(config-line)#" },
      { instrucao: "Aplique a ACL de entrada com access-class.", cmd: "access-class 10 in", saida: "", promptDepois: "Router(config-line)#" },
      { instrucao: "Exija SSH e login local.", cmd: "transport input ssh", saida: "", promptDepois: "Router(config-line)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Verifique a ACL e os matches.", cmd: "show access-lists 10", saida: "Standard IP access list 10\n    10 permit 10.1.1.10 (2 matches)", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Usar `ip access-group` nas linhas VTY — o comando certo é `access-class`.",
      "Esquecer o deny implícito e se trancar pra fora — teste antes de fechar a sessão.",
      "Aplicar na direção errada: `in` filtra quem conecta ao roteador, `out` filtra sessões saindo dele.",
    ],
  },
  {
    id: "lab-42-ntpsyslog",
    topicId: "m42-02",
    titulo: "NTP e Syslog: relógio confiável e logs centralizados",
    ferramenta: "PNETLab",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "R1 sincroniza horário com um servidor NTP interno e envia logs a um servidor Syslog.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Defina o fuso horário.", cmd: "clock timezone BRT -3", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Aponte pro servidor NTP.", cmd: "ntp server 10.1.1.5", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Ative timestamps com data/hora nos logs.", cmd: "service timestamps log datetime msec", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Aponte pro servidor Syslog.", cmd: "logging host 10.1.1.6", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Envie ao servidor eventos de nível informational (6) ou mais graves.", cmd: "logging trap informational", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Confirme a sincronização NTP.", cmd: "show ntp status", saida: "Clock is synchronized, stratum 3, reference is 10.1.1.5\nnominal freq is 250.0000 Hz, actual freq is 250.0000 Hz", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Log sem `service timestamps` — as mensagens saem sem hora, inúteis pra correlação.",
      "Firewall/ACL bloqueando UDP 123 (NTP) ou UDP 514 (Syslog).",
      "Nível de `logging trap` alto demais (só debugging) inunda o servidor.",
    ],
  },
  {
    id: "lab-10-portfast",
    topicId: "m10-02",
    titulo: "PortFast e BPDU Guard nas portas de acesso",
    ferramenta: "EVE-NG",
    dispositivo: "Switch",
    promptInicial: "Switch>",
    topologiaDescricao: "Switch de acesso: portas de usuário sobem na hora e se protegem contra switches indevidos.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Switch#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Switch(config)#" },
      { instrucao: "Ative PortFast como padrão em todas as portas de acesso.", cmd: "spanning-tree portfast default", saida: "%Warning: this command enables portfast by default on all interfaces...", promptDepois: "Switch(config)#" },
      { instrucao: "Ative BPDU Guard como padrão nas portas com PortFast.", cmd: "spanning-tree portfast bpduguard default", saida: "", promptDepois: "Switch(config)#" },
      { instrucao: "Entre numa porta de acesso específica.", cmd: "interface fa0/5", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Garanta que é porta de acesso.", cmd: "switchport mode access", saida: "", promptDepois: "Switch(config-if)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Switch#" },
      { instrucao: "Verifique o estado de STP da porta.", cmd: "show spanning-tree interface fa0/5 portfast", saida: "VLAN0001            enabled", promptDepois: "Switch#" },
    ],
    errosComuns: [
      "Ativar PortFast num link entre switches — cria risco de loop enquanto o STP não converge.",
      "BPDU Guard ativo numa porta que recebe BPDU legítima — ela vai pra err-disabled.",
      "Achar que PortFast desativa o STP na porta — ela ainda processa BPDUs, só pula os estados de espera.",
    ],
  },
  {
    id: "lab-27-ipv6addr",
    topicId: "m27-01",
    titulo: "Endereçamento IPv6 nas interfaces (global, link-local e EUI-64)",
    ferramenta: "PNETLab",
    dispositivo: "Router",
    promptInicial: "Router>",
    topologiaDescricao: "R1 com dois enlaces IPv6: um com endereço manual, outro usando EUI-64.",
    comandos: [
      { instrucao: "Entre no modo privilegiado.", cmd: "enable", saida: "", promptDepois: "Router#" },
      { instrucao: "Entre no modo de configuração global.", cmd: "configure terminal", saida: "Enter configuration commands, one per line.  End with CNTL/Z.", promptDepois: "Router(config)#" },
      { instrucao: "Habilite o roteamento IPv6.", cmd: "ipv6 unicast-routing", saida: "", promptDepois: "Router(config)#" },
      { instrucao: "Entre na primeira interface.", cmd: "interface g0/0", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Configure um endereço global unicast manual.", cmd: "ipv6 address 2001:db8:0:1::1/64", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Ative a interface.", cmd: "no shutdown", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Entre na segunda interface.", cmd: "interface g0/1", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Configure o endereço com EUI-64 (host derivado do MAC).", cmd: "ipv6 address 2001:db8:0:2::/64 eui-64", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Ative a interface.", cmd: "no shutdown", saida: "", promptDepois: "Router(config-if)#" },
      { instrucao: "Saia do modo de configuração.", cmd: "end", saida: "", promptDepois: "Router#" },
      { instrucao: "Verifique os endereços IPv6 das interfaces.", cmd: "show ipv6 interface brief", saida: "GigabitEthernet0/0     [up/up]\n    FE80::1\n    2001:DB8:0:1::1\nGigabitEthernet0/1     [up/up]\n    FE80::2D0:FFFF:FE12:3456\n    2001:DB8:0:2:2D0:FFFF:FE12:3456", promptDepois: "Router#" },
    ],
    errosComuns: [
      "Esquecer que o endereço link-local (FE80::/10) é gerado sozinho ao configurar qualquer IPv6 na interface.",
      "Confundir a ordem no EUI-64: FFFE entra no meio do MAC e o 7º bit é invertido.",
      "Não habilitar `ipv6 unicast-routing` — a interface tem endereço mas o roteador não encaminha.",
    ],
  },
];

export async function seedLabsIfNeeded() {
  const metaRef = doc(db, "content", "meta");
  const metaSnap = await getDoc(metaRef);

  if (metaSnap.exists() && metaSnap.data().labsSeededV5) {
    console.log("[seed] Labs já populados, pulando.");
    return { seeded: false };
  }

  const batch = writeBatch(db);
  labsExemplo.forEach((lab) => {
    const ref = doc(db, "content", "labs", "items", lab.id);
    batch.set(ref, lab);
  });
  batch.set(metaRef, { labsSeededV5: true, labsCount: labsExemplo.length, labsSeededV5At: serverTimestamp() }, { merge: true });

  await batch.commit();
  console.log(`[seed] ✅ ${labsExemplo.length} labs gravados`);
  return { seeded: true, count: labsExemplo.length };
}
